// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A website analysis AI agent.
 *
 * - analyzeWebsite - A function that handles the website analysis process.
 * - AnalyzeWebsiteInput - The input type for the analyzeWebsite function.
 * - AnalyzeWebsiteOutput - The return type for the analyzeWebsite function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeWebsiteInputSchema = z.object({
  url: z.string().describe('The URL of the website to analyze.'),
});
export type AnalyzeWebsiteInput = z.infer<typeof AnalyzeWebsiteInputSchema>;

const AnalyzeWebsiteOutputSchema = z.object({
  summary: z.string().describe('A summary of the website analysis, highlighting areas for speed optimization.'),
});
export type AnalyzeWebsiteOutput = z.infer<typeof AnalyzeWebsiteOutputSchema>;

export async function analyzeWebsite(input: AnalyzeWebsiteInput): Promise<AnalyzeWebsiteOutput> {
  return analyzeWebsiteFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeWebsitePrompt',
  input: {schema: AnalyzeWebsiteInputSchema},
  output: {schema: AnalyzeWebsiteOutputSchema},
  prompt: `You are an expert website performance analyst.

You will analyze the website at the given URL and provide a summary of areas for speed optimization.

URL: {{{url}}}`,
});

const analyzeWebsiteFlow = ai.defineFlow(
  {
    name: 'analyzeWebsiteFlow',
    inputSchema: AnalyzeWebsiteInputSchema,
    outputSchema: AnalyzeWebsiteOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
